server:
  port: 8662

spring:
  application:
    name: hystrix-dashboard-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
turbine:
  appConfig: SPRING-DEMO-SERVICE-FEIGN,SPRING-DEMO-SERVICE-RIBBON
  clusterNameExpression: ${TURBINE_CLUSTER_NAME_EXP:'default'}
  aggregator:
    clusterConfig: ${TURBINE_CLUSTERS:default}